name: Publish RPA

on:
  push:
    tags:
      - '*'


permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/camunda-rpa-v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Determine library to build
        id: determine-library
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          if [[ $TAG_NAME == camunda-rpa-v* ]]; then
            echo "library=camunda-rpa" >> $GITHUB_ENV
            echo "version=${TAG_NAME#camunda-rpa-v}" >> $GITHUB_ENV
          elif [[ $TAG_NAME == camunda-utils-v* ]]; then
            echo "library=camunda-utils" >> $GITHUB_ENV
            echo "version=${TAG_NAME#camunda-utils-v}" >> $GITHUB_ENV
          else
            echo "Unknown tag format: $TAG_NAME"
            exit 1
          fi

      - name: Set wheel name
        run: echo "library_underscore=$(echo ${{ env.library }} | tr '-' '_')" >> $GITHUB_ENV

      - name: Build library
        run: |
          cd ${{ env.library }}
          sed -i 's/9.9.9.dev0/${{ env.version }}/' pyproject.toml
          python -m build

      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     packages-dir: ${{ env.library }}/dist

      - name: Create GH Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Tarball Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls the upload URL from the create_release step
          asset_path: ${{ env.library }}/dist/${{ env.library_underscore }}-${{ env.version }}.tar.gz
          asset_name: ${{ env.library_underscore }}-${{ env.version }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Wheel Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls the upload URL from the create_release step
          asset_path: ${{ env.library }}/dist/${{ env.library_underscore }}-${{ env.version }}-py3-none-any.whl
          asset_name: ${{ env.library_underscore }}-${{ env.version }}-py3-none-any.whl
          asset_content_type: application/zip
