name: Publish Utils

on:
  # TODO: change to appropriate event
  pull_request:
    branches:
      - main


permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build camunda-utils
        working-directory: camunda-utils
        run: |
          python -m pip install build
          python -m build

      - name: Publish camunda-utils
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: camunda-utils/dist
